repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^docs-vitepress/
      - id: end-of-file-fixer
        exclude: ^docs-vitepress/
      - id: check-yaml
        exclude: ^conda\.recipe/meta\.yaml$
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
        language_version: python3.13
